image:
  file: .gitpod.Dockerfile

ports:
- port: 3333
  onOpen: ignore
- port: 3000
  onOpen: open-browser

tasks:
- init: yarn install # runs during prebuild
  command: yarn dev
- openMode: split-right
  command: cd app && npm install && npm start